name: spacenavpro

on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic-ros-core-focal
    steps:
    - uses: actions/checkout@v2
    - name: Build package
      run: |
        mkdir -p ~/catkin_ws/src
        cd ~/catkin_ws/src
        ln -s $GITHUB_WORKSPACE .
        cd ~/catkin_ws
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        catkin_make'
